-- Generated by scripts/render-processing-history.py; edit the generator.
CREATE VIEW mwe_processing_job_state AS
SELECT j.id AS job_id, j.tenant_id, j.knowledge_base_id,
 j.datasource_id, j.external_id, j.origin_run_id AS run_id, j.knowledge_id,
 j.kind, j.generation, j.source_revision, j.configuration_revision, j.pipeline_fingerprint,
 j.revision, j.is_current, j.is_published, j.publication_epoch, j.rollback_pin,
 j.retirement_state, j.readiness, j.completeness, j.status AS job_status, j.plan_sealed,
 COALESCE(NULLIF((j.metadata ->> 'title'), ''), NULLIF(k.title, ''), j.external_id) AS title,
 COALESCE((j.metadata ->> 'folder_path'), '') AS folder_path,
 COALESCE(ds.name, '') AS source_name, COALESCE(kb.name, '') AS kb_name,
 j.created_at, j.updated_at, j.published_at, j.finished_at,
 (SELECT COUNT(*) FROM processing_steps s WHERE s.job_id=j.id) AS steps_total,
 (SELECT COUNT(*) FROM processing_steps s WHERE s.job_id=j.id AND s.status='succeeded') AS steps_succeeded,
 (SELECT COUNT(*) FROM processing_steps s WHERE s.job_id=j.id AND s.status IN ('blocked','failed')) AS steps_problem,
 (SELECT COUNT(*) FROM processing_steps s WHERE s.job_id=j.id AND s.phase='retire' AND s.status IN ('blocked','failed','retry_wait')) AS cleanup_problem,
 (SELECT MIN(s.next_run_at) FROM processing_steps s WHERE s.job_id=j.id AND s.status IN ('retry_wait','waiting_external','enqueue_pending','queued')) AS next_retry_at,
 (SELECT MAX(s.heartbeat_at) FROM processing_steps s WHERE s.job_id=j.id) AS heartbeat_at,
 (SELECT COUNT(*) FROM resource_bindings b JOIN resources r ON r.id=b.resource_id AND r.tenant_id=b.tenant_id
  WHERE b.tenant_id=j.tenant_id AND b.owner_type='processing_job' AND b.owner_id=j.id AND r.state='active') AS resources_active,
 (SELECT COALESCE(SUM(r.bytes),0) FROM processing_storage_reservations r WHERE r.tenant_id=j.tenant_id AND r.job_id=j.id AND r.state <> 'released')
 + (SELECT COALESCE(SUM(w.estimated_bytes),0) FROM faq_index_writes w WHERE w.tenant_id=j.tenant_id AND w.job_id=j.id AND NOT w.storage_released) AS charged_bytes,
 (SELECT COALESCE(SUM(r.bytes),0) FROM processing_storage_reservations r WHERE r.tenant_id=j.tenant_id AND r.job_id=j.id AND r.kind='index' AND r.state <> 'released')
 + (SELECT COALESCE(SUM(w.estimated_bytes),0) FROM faq_index_writes w WHERE w.tenant_id=j.tenant_id AND w.job_id=j.id AND NOT w.storage_released) AS estimated_index_bytes,
 CASE WHEN (j.metadata ->> 'kind') IN ('doc','smartcanvas','sheet','smartsheet') THEN (j.metadata ->> 'kind') ELSE NULL END AS doc_type,
 (SELECT CASE WHEN jsonb_typeof(s.result->'raw_bytes')='number' THEN CAST((s.result ->> 'raw_bytes') AS BIGINT) ELSE NULL END FROM processing_steps s WHERE s.job_id=j.id AND s.stage='native_read' AND s.unit_key='body' LIMIT 1) AS native_raw_bytes, (SELECT CASE WHEN jsonb_typeof(s.result->'pages')='number' THEN CAST((s.result ->> 'pages') AS BIGINT) ELSE NULL END FROM processing_steps s WHERE s.job_id=j.id AND s.stage='native_read' AND s.unit_key='body' LIMIT 1) AS native_pages,
 (SELECT CASE WHEN jsonb_typeof(s.result->'units')='number' THEN CAST((s.result ->> 'units') AS BIGINT) ELSE NULL END FROM processing_steps s WHERE s.job_id=j.id AND s.stage='native_read' AND s.unit_key='body' LIMIT 1) AS native_units, (SELECT CASE WHEN jsonb_typeof(s.result->'images')='number' THEN CAST((s.result ->> 'images') AS BIGINT) ELSE NULL END FROM processing_steps s WHERE s.job_id=j.id AND s.stage='assets' AND s.unit_key='body' LIMIT 1) AS images,
 (SELECT CASE WHEN jsonb_typeof(s.result->'media_bytes')='number' THEN CAST((s.result ->> 'media_bytes') AS BIGINT) ELSE NULL END FROM processing_steps s WHERE s.job_id=j.id AND s.stage='assets' AND s.unit_key='body' LIMIT 1) AS media_bytes,
 (SELECT s.stage FROM processing_steps s WHERE s.job_id=j.id AND s.status IN ('failed','blocked','retry_wait','running','waiting_external','enqueue_pending','queued')
 ORDER BY CASE s.status WHEN 'failed' THEN 0 WHEN 'blocked' THEN 1 WHEN 'retry_wait' THEN 2 WHEN 'running' THEN 3 ELSE 4 END, s.created_at, s.id LIMIT 1) AS active_stage
FROM processing_jobs j
LEFT JOIN knowledges k ON k.id=j.knowledge_id AND k.tenant_id=j.tenant_id
LEFT JOIN data_sources ds ON ds.id=j.datasource_id AND ds.tenant_id=j.tenant_id
LEFT JOIN knowledge_bases kb ON kb.id=j.knowledge_base_id AND kb.tenant_id=j.tenant_id;

CREATE VIEW mwe_processing_current_document_lifecycle AS
SELECT j.*, j.job_id AS row_id, j.job_status AS status, COALESCE(j.active_stage,'') AS stage, j.updated_at AS observed_at,
 p.job_id AS published_job_id, p.generation AS published_generation,
 CASE WHEN j.is_published THEN 'current_available' WHEN p.job_id IS NOT NULL THEN 'previous_available' ELSE 'not_published' END AS availability,
 'verified_v2' AS evidence_basis
FROM mwe_processing_job_state j
LEFT JOIN mwe_processing_job_state p ON p.tenant_id=j.tenant_id AND p.knowledge_base_id=j.knowledge_base_id
 AND p.datasource_id=j.datasource_id AND p.external_id=j.external_id AND p.kind='document' AND p.is_published
WHERE j.kind='document' AND (j.is_current OR (j.is_published AND NOT EXISTS
 (SELECT 1 FROM processing_jobs n WHERE n.tenant_id=j.tenant_id AND n.knowledge_base_id=j.knowledge_base_id
 AND n.datasource_id=j.datasource_id AND n.external_id=j.external_id AND n.kind='document' AND n.is_current)))
UNION ALL
SELECT '' AS job_id, k.tenant_id, k.knowledge_base_id, (k.metadata ->> 'datasource_id'),
 COALESCE((k.metadata ->> 'external_id'),''), '' AS run_id, k.id AS knowledge_id,
 'document' AS kind, NULL AS generation, '' AS source_revision, '' AS configuration_revision, '' AS pipeline_fingerprint,
 NULL AS revision, FALSE AS is_current, FALSE AS is_published, NULL AS publication_epoch, FALSE AS rollback_pin,
 'legacy_unverified' AS retirement_state, 'unknown' AS readiness, 'unknown' AS completeness, k.parse_status, FALSE AS plan_sealed,
 k.title, '' AS folder_path, COALESCE(ds.name,''), COALESCE(kb.name,''),
 k.created_at, k.updated_at, NULL AS published_at, NULL AS finished_at,
 NULL AS steps_total, NULL AS steps_succeeded, NULL AS steps_problem, NULL AS cleanup_problem,
 NULL AS next_retry_at, NULL AS heartbeat_at, NULL AS resources_active, NULL AS charged_bytes, NULL AS estimated_index_bytes,
 NULL AS doc_type, NULL AS native_raw_bytes, NULL AS native_pages, NULL AS native_units, NULL AS images, NULL AS media_bytes, NULL AS active_stage,
 'legacy:' || k.id AS row_id, k.parse_status AS status, '' AS stage, k.updated_at AS observed_at,
 NULL AS published_job_id, NULL AS published_generation,
 CASE WHEN k.enable_status='enabled' AND k.parse_status IN ('completed','finalizing') THEN 'legacy_available' ELSE 'legacy_unverified' END AS availability,
 'legacy_unverified' AS evidence_basis
FROM knowledges k
LEFT JOIN data_sources ds ON ds.id=(k.metadata ->> 'datasource_id') AND ds.tenant_id=k.tenant_id
LEFT JOIN knowledge_bases kb ON kb.id=k.knowledge_base_id AND kb.tenant_id=k.tenant_id
WHERE k.deleted_at IS NULL AND COALESCE((k.metadata ->> 'processing_protocol'),'')<>'2'
 AND COALESCE((k.metadata ->> 'datasource_id'),'')<>'';

CREATE VIEW mwe_processing_current_run_progress AS
SELECT j.*, j.job_id AS row_id, j.job_status AS status, 'scan' AS stage, j.updated_at AS observed_at,
 (SELECT COUNT(*) FROM sync_run_items i WHERE i.tenant_id=j.tenant_id AND i.run_id=j.run_id AND i.kind='document') AS documents, (SELECT COUNT(*) FROM sync_run_items i WHERE i.tenant_id=j.tenant_id AND i.run_id=j.run_id AND i.kind='container') AS containers, (SELECT COUNT(*) FROM sync_run_items i WHERE i.tenant_id=j.tenant_id AND i.run_id=j.run_id AND i.kind='link') AS external_links, (SELECT COUNT(*) FROM sync_run_items i JOIN processing_jobs d ON d.id=i.job_id AND d.tenant_id=i.tenant_id
 WHERE i.tenant_id=j.tenant_id AND i.run_id=j.run_id AND i.kind='document' AND d.status='succeeded') AS documents_succeeded, (SELECT COUNT(*) FROM sync_run_items i JOIN processing_jobs d ON d.id=i.job_id AND d.tenant_id=i.tenant_id
 WHERE i.tenant_id=j.tenant_id AND i.run_id=j.run_id AND i.kind='document' AND d.status='blocked') AS documents_blocked, (SELECT COUNT(*) FROM sync_run_items i JOIN processing_jobs d ON d.id=i.job_id AND d.tenant_id=i.tenant_id
 WHERE i.tenant_id=j.tenant_id AND i.run_id=j.run_id AND i.kind='document' AND d.status='failed') AS documents_failed, (SELECT COUNT(*) FROM sync_run_items i JOIN processing_jobs d ON d.id=i.job_id AND d.tenant_id=i.tenant_id
 WHERE i.tenant_id=j.tenant_id AND i.run_id=j.run_id AND i.kind='document' AND d.status='canceled') AS documents_canceled, (SELECT COUNT(*) FROM sync_run_items i JOIN processing_jobs d ON d.id=i.job_id AND d.tenant_id=i.tenant_id
 WHERE i.tenant_id=j.tenant_id AND i.run_id=j.run_id AND i.kind='document' AND d.status='superseded') AS documents_superseded, (SELECT COUNT(*) FROM sync_run_items i JOIN processing_jobs d ON d.id=i.job_id AND d.tenant_id=i.tenant_id
 WHERE i.tenant_id=j.tenant_id AND i.run_id=j.run_id AND i.kind='document' AND d.status='skipped') AS documents_skipped, (SELECT COUNT(*) FROM sync_run_items i WHERE i.tenant_id=j.tenant_id AND i.run_id=j.run_id AND i.kind='document'
 AND COALESCE(i.job_id,'')='') AS documents_unadmitted, (SELECT COUNT(*) FROM sync_run_items i JOIN processing_jobs d ON d.id=i.job_id AND d.tenant_id=i.tenant_id
 WHERE i.tenant_id=j.tenant_id AND i.run_id=j.run_id AND i.kind='document'
 AND d.status NOT IN ('succeeded','blocked','failed','canceled','superseded','skipped')) AS documents_active,
 (SELECT e.to_state FROM processing_events e WHERE e.tenant_id=j.tenant_id AND e.job_id=j.job_id AND e.event_type='run_finished' ORDER BY e.id LIMIT 1) AS original_finished_status,
 (SELECT e.created_at FROM processing_events e WHERE e.tenant_id=j.tenant_id AND e.job_id=j.job_id AND e.event_type='run_finished' ORDER BY e.id LIMIT 1) AS original_finished_at
FROM mwe_processing_job_state j WHERE j.kind='scan' AND
 (j.job_status NOT IN ('succeeded','canceled','superseded','skipped','failed') OR NOT EXISTS
 (SELECT 1 FROM processing_jobs n WHERE n.kind='scan' AND n.tenant_id=j.tenant_id
 AND n.datasource_id=j.datasource_id AND n.created_at>j.created_at));

CREATE VIEW mwe_processing_stage_retry_queue AS
SELECT j.*, s.id AS row_id, s.id AS step_id, s.status, s.stage, s.phase, s.unit_key,
 s.step_attempt, s.dispatch_seq, s.retry_count, s.max_retries, s.next_run_at, s.deadline_at, s.lease_expires_at,
 s.required_for_ready, s.required_for_completion, s.error_class, s.error_code, s.last_error_event_id,
 s.updated_at AS observed_at
FROM mwe_processing_job_state j JOIN processing_steps s ON s.job_id=j.job_id
WHERE s.status IN ('enqueue_pending','queued','running','waiting_external','retry_wait','failed','blocked');

CREATE VIEW mwe_processing_attempt_timeline AS
SELECT j.*, CAST(e.id AS TEXT) AS row_id, e.id AS event_id, e.step_id,
 COALESCE(s.stage,'') AS stage, e.event_type, e.to_state AS status, e.job_revision AS event_revision,
 e.step_attempt, e.dispatch_seq, e.from_state, e.error_class, e.error_code,
 e.actor, e.action, e.operation_request_id, e.queue_task_id, e.trace_id,
 e.resolves_event_id, e.resolution_type, e.created_at AS observed_at
FROM processing_events e JOIN mwe_processing_job_state j ON j.job_id=e.job_id AND j.tenant_id=e.tenant_id
LEFT JOIN processing_steps s ON s.id=e.step_id AND s.job_id=e.job_id;

CREATE VIEW mwe_processing_unresolved_incidents AS
SELECT e.* FROM mwe_processing_attempt_timeline e
WHERE COALESCE(e.error_code,'')<>'' AND NOT EXISTS
 (SELECT 1 FROM processing_events r WHERE r.tenant_id=e.tenant_id AND r.job_id=e.job_id
 AND r.resolves_event_id=e.event_id AND COALESCE(r.resolution_type,'')<>'');

CREATE VIEW mwe_processing_lifecycle_inconsistencies AS
SELECT j.*, 'READY_NOT_PUBLISHED:' || j.job_id AS row_id, 'READY_NOT_PUBLISHED' AS status, '' AS stage,
 '' AS step_id, j.updated_at AS observed_at FROM mwe_processing_job_state j  WHERE j.is_current AND NOT j.is_published AND j.readiness='ready' AND EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP - j.updated_at))>300
UNION ALL
SELECT j.*, 'PLAN_UNSEALED:' || j.job_id AS row_id, 'PLAN_UNSEALED' AS status, '' AS stage,
 '' AS step_id, j.updated_at AS observed_at FROM mwe_processing_job_state j  WHERE j.is_current AND NOT j.plan_sealed AND EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP - j.created_at))>300
UNION ALL
SELECT j.*, 'LEASE_EXPIRED:' || s.id AS row_id, 'LEASE_EXPIRED' AS status, s.stage AS stage,
 s.id AS step_id, j.updated_at AS observed_at FROM mwe_processing_job_state j JOIN processing_steps s ON s.job_id=j.job_id WHERE s.status='running' AND EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP - s.lease_expires_at))>0
UNION ALL
SELECT j.*, 'NO_PROGRESS:' || s.id AS row_id, 'NO_PROGRESS' AS status, s.stage AS stage,
 s.id AS step_id, j.updated_at AS observed_at FROM mwe_processing_job_state j JOIN processing_steps s ON s.job_id=j.job_id WHERE s.status='running' AND EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP - s.lease_expires_at))<0 AND EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP - s.progress_at))>300
UNION ALL
SELECT j.*, 'RETRY_OVERDUE:' || s.id AS row_id, 'RETRY_OVERDUE' AS status, s.stage AS stage,
 s.id AS step_id, j.updated_at AS observed_at FROM mwe_processing_job_state j JOIN processing_steps s ON s.job_id=j.job_id WHERE s.status='retry_wait' AND EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP - s.next_run_at))>120
UNION ALL
SELECT j.*, 'PROJECTION_NOT_CONVERGED:' || s.id AS row_id, 'PROJECTION_NOT_CONVERGED' AS status, s.stage AS stage,
 s.id AS step_id, j.updated_at AS observed_at FROM mwe_processing_job_state j JOIN processing_steps s ON s.job_id=j.job_id WHERE j.is_published AND s.phase='projection' AND s.stage<>'retire_previous' AND s.status NOT IN ('succeeded','skipped') AND EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP - j.published_at))>300
UNION ALL
SELECT j.*, 'OUTBOX_OVERDUE:' || s.id AS row_id, 'OUTBOX_OVERDUE' AS status, s.stage AS stage,
 s.id AS step_id, j.updated_at AS observed_at FROM mwe_processing_job_state j JOIN processing_steps s ON s.job_id=j.job_id JOIN task_pending_ops o ON o.tenant_id=j.tenant_id AND o.step_id=s.id AND o.step_attempt=s.step_attempt AND o.dispatch_seq=s.dispatch_seq WHERE s.status IN ('enqueue_pending','queued') AND o.delivered_at IS NULL AND o.op='deliver'
 AND EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP - o.available_at))>120
UNION ALL
SELECT j.*, 'DEAD_LETTER_RUNNING:' || s.id AS row_id, 'DEAD_LETTER_RUNNING' AS status, s.stage AS stage,
 s.id AS step_id, j.updated_at AS observed_at FROM mwe_processing_job_state j JOIN processing_steps s ON s.job_id=j.job_id WHERE s.status='running' AND EXISTS (SELECT 1 FROM task_dead_letters d
 WHERE d.tenant_id=j.tenant_id AND (d.payload ->> 'job_id')=j.job_id AND (d.payload ->> 'step_id')=s.id
 AND (d.payload ->> 'generation')=CAST(j.generation AS TEXT)
 AND (d.payload ->> 'step_attempt')=CAST(s.step_attempt AS TEXT) AND (d.payload ->> 'dispatch_seq')=CAST(s.dispatch_seq AS TEXT))
UNION ALL
SELECT j.*, 'RESOURCE_MISSING:' || j.job_id AS row_id, 'RESOURCE_MISSING' AS status, '' AS stage,
 '' AS step_id, j.updated_at AS observed_at FROM mwe_processing_job_state j  WHERE j.retirement_state='retained' AND EXISTS (SELECT 1 FROM resource_bindings b
 LEFT JOIN resources r ON r.id=b.resource_id AND r.tenant_id=b.tenant_id
 WHERE b.tenant_id=j.tenant_id AND b.owner_type='processing_job' AND b.owner_id=j.job_id
 AND (r.id IS NULL OR r.state<>'active' OR r.deleted_at IS NOT NULL))
UNION ALL
SELECT j.*, 'COMPATIBILITY_DRIFT:' || j.job_id AS row_id, 'COMPATIBILITY_DRIFT' AS status, '' AS stage,
 '' AS step_id, j.updated_at AS observed_at FROM mwe_processing_job_state j LEFT JOIN knowledges k ON k.id=j.knowledge_id AND k.tenant_id=j.tenant_id WHERE j.is_published AND (k.id IS NULL OR k.deleted_at IS NOT NULL OR k.parse_status NOT IN ('completed','finalizing') OR (j.job_status='succeeded' AND k.parse_status<>'completed') OR k.enable_status<>'enabled')
UNION ALL
SELECT j.*, 'RETIREMENT_BLOCKED:' || s.id AS row_id, 'RETIREMENT_BLOCKED' AS status, s.stage AS stage,
 s.id AS step_id, j.updated_at AS observed_at FROM mwe_processing_job_state j JOIN processing_steps s ON s.job_id=j.job_id WHERE s.phase='retire' AND s.status IN ('failed','blocked')
UNION ALL
SELECT j.*, 'FAQ_GC_STUCK:' || w.id AS row_id, 'FAQ_GC_STUCK' AS status, '' AS stage,
 '' AS step_id, j.updated_at AS observed_at FROM mwe_processing_job_state j JOIN faq_index_writes w ON w.job_id=j.job_id AND w.tenant_id=j.tenant_id WHERE w.state='deleting' AND EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP - w.updated_at))>300
UNION ALL
SELECT j.*, 'RESOURCE_GC_STUCK:' || r.id AS row_id, 'RESOURCE_GC_STUCK' AS status, '' AS stage,
 '' AS step_id, j.updated_at AS observed_at FROM mwe_processing_job_state j JOIN resources r ON r.creation_job_id=j.job_id AND r.tenant_id=j.tenant_id WHERE r.state='deleting' AND EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP - r.updated_at))>300;

CREATE TABLE processing_history_snapshots (
 id TEXT PRIMARY KEY, tenant_id BIGINT NOT NULL, principal TEXT NOT NULL, kb_scope TEXT NOT NULL,
 view_name TEXT NOT NULL, filter_digest TEXT NOT NULL, total INTEGER NOT NULL CHECK(total BETWEEN 0 AND 10000),
 created_at TIMESTAMPTZ NOT NULL, expires_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX idx_processing_snapshot_principal ON processing_history_snapshots(tenant_id, principal, created_at);
CREATE INDEX idx_processing_snapshot_expiry ON processing_history_snapshots(expires_at);
CREATE TABLE processing_history_rows (
 snapshot_id TEXT NOT NULL REFERENCES processing_history_snapshots(id) ON DELETE CASCADE,
 rank INTEGER NOT NULL, payload TEXT NOT NULL, PRIMARY KEY(snapshot_id, rank)
);
