DROP VIEW mwe_processing_lifecycle_inconsistencies;
DROP VIEW mwe_processing_unresolved_incidents;
DROP VIEW mwe_processing_attempt_timeline;
DROP VIEW mwe_processing_stage_retry_queue;
DROP VIEW mwe_processing_current_run_progress;
DROP VIEW mwe_processing_current_document_lifecycle;
DROP VIEW mwe_processing_job_state;
-- Generated by scripts/render-processing-history.py; edit the generator.
CREATE VIEW mwe_processing_legacy_run_state AS
SELECT s.id AS run_id,s.tenant_id,ds.knowledge_base_id,ds.id AS datasource_id,
 ds.name AS source_name,kb.name AS kb_name,s.status AS run_status,s.started_at,s.updated_at,s.finished_at,
 s.items_total,s.items_created,s.items_updated,s.items_skipped,s.items_failed,s.result,
 (SELECT MAX(d.id) FROM task_dead_letters d WHERE d.tenant_id=s.tenant_id AND d.task_type='datasource:sync'
 AND CAST(json_extract(d.payload, '$.data_source_id') AS TEXT)=ds.id AND CAST(json_extract(d.payload, '$.sync_log_id') AS TEXT)=s.id) AS dead_letter_id
FROM sync_logs s JOIN data_sources ds ON ds.id=s.data_source_id AND ds.tenant_id=s.tenant_id
LEFT JOIN knowledge_bases kb ON kb.id=ds.knowledge_base_id AND kb.tenant_id=s.tenant_id
WHERE ds.type='tencent_docs' AND NOT EXISTS (SELECT 1 FROM processing_jobs j WHERE j.kind='scan' AND j.tenant_id=s.tenant_id AND j.datasource_id=ds.id AND j.origin_run_id=s.id);

CREATE VIEW mwe_processing_legacy_error_state AS
SELECT r.run_id,r.tenant_id,r.knowledge_base_id,r.datasource_id,r.source_name,r.kb_name,r.run_status,r.started_at,r.updated_at,r.finished_at,r.dead_letter_id,
 (CAST(e.key AS INTEGER)+1) AS error_ordinal,weknora_sha256(json_quote(json_extract(r.result,'$.errors['||e.key||']'))) AS error_digest,
 COALESCE(CASE WHEN e.type='object' THEN CAST(json_extract(e.value, '$.external_id') AS TEXT) ELSE '' END,'') AS external_id,COALESCE(CASE WHEN e.type='object' THEN CAST(json_extract(e.value, '$.file_id') AS TEXT) ELSE '' END,'') AS file_id,
 COALESCE(CASE WHEN e.type='object' THEN CAST(json_extract(e.value, '$.title') AS TEXT) ELSE '' END,'') AS title,
 CASE WHEN LENGTH(CASE WHEN e.type='object' THEN CAST(json_extract(e.value, '$.stage') AS TEXT) ELSE '' END) BETWEEN 1 AND 64 AND CASE WHEN e.type='object' THEN CAST(json_extract(e.value, '$.stage') AS TEXT) ELSE '' END NOT GLOB '*[^a-z0-9_]*' THEN CASE WHEN e.type='object' THEN CAST(json_extract(e.value, '$.stage') AS TEXT) ELSE '' END ELSE '' END AS stage,
 CASE WHEN LENGTH(CASE WHEN e.type='object' THEN CAST(json_extract(e.value, '$.code') AS TEXT) ELSE '' END) BETWEEN 1 AND 80 AND CASE WHEN e.type='object' THEN CAST(json_extract(e.value, '$.code') AS TEXT) ELSE '' END NOT GLOB '*[^A-Z0-9_]*' THEN CASE WHEN e.type='object' THEN CAST(json_extract(e.value, '$.code') AS TEXT) ELSE '' END ELSE '' END AS error_code,
 CASE WHEN LENGTH(CASE WHEN e.type='object' THEN CAST(json_extract(e.value, '$.category') AS TEXT) ELSE '' END) BETWEEN 1 AND 80 AND CASE WHEN e.type='object' THEN CAST(json_extract(e.value, '$.category') AS TEXT) ELSE '' END NOT GLOB '*[^A-Z0-9_]*' THEN CASE WHEN e.type='object' THEN CAST(json_extract(e.value, '$.category') AS TEXT) ELSE '' END ELSE '' END AS error_class,
 CASE WHEN CASE WHEN e.type='object' THEN CAST(json_extract(e.value, '$.retry_state') AS TEXT) ELSE '' END IN ('scheduled','exhausted','failed','pending','running','completed') THEN CASE WHEN e.type='object' THEN CAST(json_extract(e.value, '$.retry_state') AS TEXT) ELSE '' END ELSE '' END AS retry_state,
 CASE WHEN julianday(CASE WHEN e.type='object' THEN CAST(json_extract(e.value, '$.occurred_at') AS TEXT) ELSE '' END) IS NOT NULL THEN CASE WHEN e.type='object' THEN CAST(json_extract(e.value, '$.occurred_at') AS TEXT) ELSE '' END ELSE r.started_at END AS observed_at
FROM mwe_processing_legacy_run_state r CROSS JOIN json_each(CASE WHEN json_type(r.result,'$.errors')='array' THEN json_extract(r.result,'$.errors') ELSE '[]' END) e;

CREATE VIEW mwe_processing_legacy_evidence_state AS
SELECT e.*,p.id AS evidence_id,p.action,p.actor,p.operation_request_id,p.job_id AS linked_job_id,p.knowledge_id,
 p.source_revision,p.attempt,p.created_at AS evidence_at
FROM mwe_processing_legacy_error_state e JOIN processing_legacy_evidence p
 ON p.tenant_id=e.tenant_id AND p.knowledge_base_id=e.knowledge_base_id AND p.datasource_id=e.datasource_id
 AND p.run_id=e.run_id AND p.error_ordinal=e.error_ordinal AND p.error_digest=e.error_digest;

CREATE VIEW mwe_processing_job_state AS
SELECT j.id AS job_id, j.tenant_id, j.knowledge_base_id,
 j.datasource_id, j.external_id, j.origin_run_id AS run_id, j.knowledge_id,
 j.kind, j.generation, j.source_revision, j.configuration_revision, j.pipeline_fingerprint,
 j.revision, j.is_current, j.is_published, j.publication_epoch, j.rollback_pin,
 j.retirement_state, j.readiness, j.completeness, j.status AS job_status, j.plan_sealed,
 COALESCE(NULLIF(CAST(json_extract(j.metadata, '$.title') AS TEXT), ''), NULLIF(k.title, ''), j.external_id) AS title,
 COALESCE(CAST(json_extract(j.metadata, '$.folder_path') AS TEXT), '') AS folder_path,
 COALESCE(ds.name, '') AS source_name, COALESCE(kb.name, '') AS kb_name,
 j.created_at, j.updated_at, j.published_at, j.finished_at,
 (SELECT COUNT(*) FROM processing_steps s WHERE s.job_id=j.id) AS steps_total,
 (SELECT COUNT(*) FROM processing_steps s WHERE s.job_id=j.id AND s.status='succeeded') AS steps_succeeded,
 (SELECT COUNT(*) FROM processing_steps s WHERE s.job_id=j.id AND s.status IN ('blocked','failed')) AS steps_problem,
 (SELECT COUNT(*) FROM processing_steps s WHERE s.job_id=j.id AND s.phase='retire' AND s.status IN ('blocked','failed','retry_wait')) AS cleanup_problem,
 (SELECT MIN(s.next_run_at) FROM processing_steps s WHERE s.job_id=j.id AND s.status IN ('retry_wait','waiting_external','enqueue_pending','queued')) AS next_retry_at,
 (SELECT MAX(s.heartbeat_at) FROM processing_steps s WHERE s.job_id=j.id) AS heartbeat_at,
 (SELECT COUNT(*) FROM resource_bindings b JOIN resources r ON r.id=b.resource_id AND r.tenant_id=b.tenant_id
  WHERE b.tenant_id=j.tenant_id AND b.owner_type='processing_job' AND b.owner_id=j.id AND r.state='active') AS resources_active,
 (SELECT COALESCE(SUM(r.bytes),0) FROM processing_storage_reservations r WHERE r.tenant_id=j.tenant_id AND r.job_id=j.id AND r.state <> 'released')
 + (SELECT COALESCE(SUM(w.estimated_bytes),0) FROM faq_index_writes w WHERE w.tenant_id=j.tenant_id AND w.job_id=j.id AND NOT w.storage_released) AS charged_bytes,
 (SELECT COALESCE(SUM(r.bytes),0) FROM processing_storage_reservations r WHERE r.tenant_id=j.tenant_id AND r.job_id=j.id AND r.kind='index' AND r.state <> 'released')
 + (SELECT COALESCE(SUM(w.estimated_bytes),0) FROM faq_index_writes w WHERE w.tenant_id=j.tenant_id AND w.job_id=j.id AND NOT w.storage_released) AS estimated_index_bytes,
 CASE WHEN CAST(json_extract(j.metadata, '$.kind') AS TEXT) IN ('doc','smartcanvas','sheet','smartsheet','resource') THEN CAST(json_extract(j.metadata, '$.kind') AS TEXT) ELSE NULL END AS doc_type,
 (SELECT CASE WHEN json_type(s.result, '$.raw_bytes')='integer' THEN CAST(CAST(json_extract(s.result, '$.raw_bytes') AS TEXT) AS BIGINT) ELSE NULL END FROM processing_steps s WHERE s.job_id=j.id AND s.stage='native_read' AND s.unit_key='body' LIMIT 1) AS native_raw_bytes, (SELECT CASE WHEN json_type(s.result, '$.pages')='integer' THEN CAST(CAST(json_extract(s.result, '$.pages') AS TEXT) AS BIGINT) ELSE NULL END FROM processing_steps s WHERE s.job_id=j.id AND s.stage='native_read' AND s.unit_key='body' LIMIT 1) AS native_pages,
 (SELECT CASE WHEN json_type(s.result, '$.units')='integer' THEN CAST(CAST(json_extract(s.result, '$.units') AS TEXT) AS BIGINT) ELSE NULL END FROM processing_steps s WHERE s.job_id=j.id AND s.stage='native_read' AND s.unit_key='body' LIMIT 1) AS native_units, (SELECT CASE WHEN json_type(s.result, '$.images')='integer' THEN CAST(CAST(json_extract(s.result, '$.images') AS TEXT) AS BIGINT) ELSE NULL END FROM processing_steps s WHERE s.job_id=j.id AND s.stage='assets' AND s.unit_key='body' LIMIT 1) AS images,
 (SELECT CASE WHEN json_type(s.result, '$.media_bytes')='integer' THEN CAST(CAST(json_extract(s.result, '$.media_bytes') AS TEXT) AS BIGINT) ELSE NULL END FROM processing_steps s WHERE s.job_id=j.id AND s.stage='assets' AND s.unit_key='body' LIMIT 1) AS media_bytes,
 (SELECT s.stage FROM processing_steps s WHERE s.job_id=j.id AND s.status IN ('failed','blocked','retry_wait','running','waiting_external','enqueue_pending','queued')
 ORDER BY CASE s.status WHEN 'failed' THEN 0 WHEN 'blocked' THEN 1 WHEN 'retry_wait' THEN 2 WHEN 'running' THEN 3 ELSE 4 END, s.created_at, s.id LIMIT 1) AS active_stage
FROM processing_jobs j
LEFT JOIN knowledges k ON k.id=j.knowledge_id AND k.tenant_id=j.tenant_id
LEFT JOIN data_sources ds ON ds.id=j.datasource_id AND ds.tenant_id=j.tenant_id
LEFT JOIN knowledge_bases kb ON kb.id=j.knowledge_base_id AND kb.tenant_id=j.tenant_id;

CREATE VIEW mwe_processing_current_document_lifecycle AS
SELECT v.*,e.error_ordinal AS original_error_ordinal,e.error_digest AS original_error_digest,
 p.linked_job_id,p.action AS legacy_action,p.actor AS legacy_actor,p.evidence_at AS legacy_evidence_at,
 l.dead_letter_id AS legacy_dead_letter_id,l.run_status AS legacy_run_status
FROM (SELECT j.*, j.job_id AS row_id, j.job_status AS status, COALESCE(j.active_stage,'') AS stage, j.updated_at AS observed_at,
 p.job_id AS published_job_id, p.generation AS published_generation,
 CASE WHEN j.is_published THEN 'current_available' WHEN p.job_id IS NOT NULL THEN 'previous_available' ELSE 'not_published' END AS availability,
 'verified_v2' AS evidence_basis
FROM mwe_processing_job_state j
LEFT JOIN mwe_processing_job_state p ON p.tenant_id=j.tenant_id AND p.knowledge_base_id=j.knowledge_base_id
 AND p.datasource_id=j.datasource_id AND p.external_id=j.external_id AND p.kind='document' AND p.is_published
WHERE j.kind='document' AND (j.is_current OR (j.is_published AND NOT EXISTS
 (SELECT 1 FROM processing_jobs n WHERE n.tenant_id=j.tenant_id AND n.knowledge_base_id=j.knowledge_base_id
 AND n.datasource_id=j.datasource_id AND n.external_id=j.external_id AND n.kind='document' AND n.is_current)))
UNION ALL
SELECT '' AS job_id, k.tenant_id, k.knowledge_base_id, CAST(json_extract(k.metadata, '$.datasource_id') AS TEXT),
 COALESCE(CAST(json_extract(k.metadata, '$.external_id') AS TEXT),''), '' AS run_id, k.id AS knowledge_id,
 'document' AS kind, NULL AS generation, '' AS source_revision, '' AS configuration_revision, '' AS pipeline_fingerprint,
 NULL AS revision, FALSE AS is_current, FALSE AS is_published, NULL AS publication_epoch, FALSE AS rollback_pin,
 'legacy_unverified' AS retirement_state, 'unknown' AS readiness, 'unknown' AS completeness, k.parse_status, FALSE AS plan_sealed,
 k.title, '' AS folder_path, COALESCE(ds.name,''), COALESCE(kb.name,''),
 k.created_at, k.updated_at, NULL AS published_at, NULL AS finished_at,
 NULL AS steps_total, NULL AS steps_succeeded, NULL AS steps_problem, NULL AS cleanup_problem,
 NULL AS next_retry_at, NULL AS heartbeat_at, NULL AS resources_active, NULL AS charged_bytes, NULL AS estimated_index_bytes,
 NULL AS doc_type, NULL AS native_raw_bytes, NULL AS native_pages, NULL AS native_units, NULL AS images, NULL AS media_bytes, NULL AS active_stage,
 'legacy:' || k.id AS row_id, k.parse_status AS status, '' AS stage, k.updated_at AS observed_at,
 NULL AS published_job_id, NULL AS published_generation,
 CASE WHEN k.enable_status='enabled' AND k.parse_status IN ('completed','finalizing') THEN 'legacy_available' ELSE 'legacy_unverified' END AS availability,
 'legacy_unverified' AS evidence_basis
FROM knowledges k
LEFT JOIN data_sources ds ON ds.id=CAST(json_extract(k.metadata, '$.datasource_id') AS TEXT) AND ds.tenant_id=k.tenant_id
LEFT JOIN knowledge_bases kb ON kb.id=k.knowledge_base_id AND kb.tenant_id=k.tenant_id
WHERE k.deleted_at IS NULL AND COALESCE(CAST(json_extract(k.metadata, '$.processing_protocol') AS TEXT),'')<>'2'
 AND COALESCE(CAST(json_extract(k.metadata, '$.datasource_id') AS TEXT),'')<>'') v
LEFT JOIN mwe_processing_legacy_run_state l ON v.kind='legacy' AND l.tenant_id=v.tenant_id AND l.run_id=v.run_id AND l.datasource_id=v.datasource_id
LEFT JOIN mwe_processing_legacy_error_state e ON l.tenant_id=e.tenant_id AND l.run_id=e.run_id AND
 (v.row_id IN ('legacy-error:'||e.run_id||':'||CAST(e.error_ordinal AS TEXT),'legacy-scheduled:'||e.run_id||':'||CAST(e.error_ordinal AS TEXT))
 OR EXISTS (SELECT 1 FROM mwe_processing_legacy_evidence_state event WHERE event.tenant_id=e.tenant_id AND event.run_id=e.run_id AND event.error_ordinal=e.error_ordinal AND v.row_id='legacy-evidence:'||event.evidence_id))
LEFT JOIN mwe_processing_legacy_evidence_state p ON p.evidence_id=(SELECT receipt.evidence_id FROM mwe_processing_legacy_evidence_state receipt
 WHERE receipt.tenant_id=e.tenant_id AND receipt.run_id=e.run_id AND receipt.error_ordinal=e.error_ordinal AND receipt.error_digest=e.error_digest
 AND (v.row_id NOT LIKE 'legacy-evidence:%' OR v.row_id='legacy-evidence:'||receipt.evidence_id)
 ORDER BY receipt.evidence_at DESC,receipt.evidence_id DESC LIMIT 1);

CREATE VIEW mwe_processing_current_run_progress AS
SELECT v.*,CASE WHEN v.kind='legacy' THEN 'legacy_record' ELSE 'verified_v2' END AS evidence_basis,e.error_ordinal AS original_error_ordinal,e.error_digest AS original_error_digest,
 p.linked_job_id,p.action AS legacy_action,p.actor AS legacy_actor,p.evidence_at AS legacy_evidence_at,
 l.dead_letter_id AS legacy_dead_letter_id,l.run_status AS legacy_run_status
FROM (SELECT j.*, j.job_id AS row_id, j.job_status AS status, 'scan' AS stage, j.updated_at AS observed_at,
 (SELECT COUNT(*) FROM sync_run_items i WHERE i.tenant_id=j.tenant_id AND i.run_id=j.run_id AND i.kind='document') AS documents, (SELECT COUNT(*) FROM sync_run_items i WHERE i.tenant_id=j.tenant_id AND i.run_id=j.run_id AND i.kind='container') AS containers, (SELECT COUNT(*) FROM sync_run_items i WHERE i.tenant_id=j.tenant_id AND i.run_id=j.run_id AND i.kind='link') AS external_links, (SELECT COUNT(*) FROM sync_run_items i JOIN processing_jobs d ON d.id=i.job_id AND d.tenant_id=i.tenant_id
 WHERE i.tenant_id=j.tenant_id AND i.run_id=j.run_id AND i.kind='document' AND d.status='succeeded') AS documents_succeeded, (SELECT COUNT(*) FROM sync_run_items i JOIN processing_jobs d ON d.id=i.job_id AND d.tenant_id=i.tenant_id
 WHERE i.tenant_id=j.tenant_id AND i.run_id=j.run_id AND i.kind='document' AND d.status='blocked') AS documents_blocked, (SELECT COUNT(*) FROM sync_run_items i JOIN processing_jobs d ON d.id=i.job_id AND d.tenant_id=i.tenant_id
 WHERE i.tenant_id=j.tenant_id AND i.run_id=j.run_id AND i.kind='document' AND d.status='failed') AS documents_failed, (SELECT COUNT(*) FROM sync_run_items i JOIN processing_jobs d ON d.id=i.job_id AND d.tenant_id=i.tenant_id
 WHERE i.tenant_id=j.tenant_id AND i.run_id=j.run_id AND i.kind='document' AND d.status='canceled') AS documents_canceled, (SELECT COUNT(*) FROM sync_run_items i JOIN processing_jobs d ON d.id=i.job_id AND d.tenant_id=i.tenant_id
 WHERE i.tenant_id=j.tenant_id AND i.run_id=j.run_id AND i.kind='document' AND d.status='superseded') AS documents_superseded, (SELECT COUNT(*) FROM sync_run_items i JOIN processing_jobs d ON d.id=i.job_id AND d.tenant_id=i.tenant_id
 WHERE i.tenant_id=j.tenant_id AND i.run_id=j.run_id AND i.kind='document' AND d.status='skipped') AS documents_skipped, (SELECT COUNT(*) FROM sync_run_items i WHERE i.tenant_id=j.tenant_id AND i.run_id=j.run_id AND i.kind='document'
 AND COALESCE(i.job_id,'')='') AS documents_unadmitted, (SELECT COUNT(*) FROM sync_run_items i JOIN processing_jobs d ON d.id=i.job_id AND d.tenant_id=i.tenant_id
 WHERE i.tenant_id=j.tenant_id AND i.run_id=j.run_id AND i.kind='document'
 AND d.status NOT IN ('succeeded','blocked','failed','canceled','superseded','skipped')) AS documents_active,
 (SELECT e.to_state FROM processing_events e WHERE e.tenant_id=j.tenant_id AND e.job_id=j.job_id AND e.event_type='run_finished' ORDER BY e.id LIMIT 1) AS original_finished_status,
 (SELECT e.created_at FROM processing_events e WHERE e.tenant_id=j.tenant_id AND e.job_id=j.job_id AND e.event_type='run_finished' ORDER BY e.id LIMIT 1) AS original_finished_at
FROM mwe_processing_job_state j WHERE j.kind='scan' AND
 (j.job_status NOT IN ('succeeded','canceled','superseded','skipped','failed') OR NOT EXISTS
 (SELECT 1 FROM processing_jobs n WHERE n.kind='scan' AND n.tenant_id=j.tenant_id
 AND n.datasource_id=j.datasource_id AND n.created_at>j.created_at))
UNION ALL
SELECT '',l.tenant_id,l.knowledge_base_id,l.datasource_id,'',l.run_id,'','legacy',NULL,'','','',NULL,FALSE,FALSE,NULL,FALSE,'legacy_unverified','unknown','unknown',l.run_status,FALSE,l.source_name||' / '||l.run_id,'',l.source_name,l.kb_name,l.started_at,l.updated_at,NULL,l.finished_at,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'legacy-run:'||l.run_id,l.run_status,'legacy_scan',l.updated_at,
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,l.run_status,l.finished_at
FROM mwe_processing_legacy_run_state l) v
LEFT JOIN mwe_processing_legacy_run_state l ON v.kind='legacy' AND l.tenant_id=v.tenant_id AND l.run_id=v.run_id AND l.datasource_id=v.datasource_id
LEFT JOIN mwe_processing_legacy_error_state e ON l.tenant_id=e.tenant_id AND l.run_id=e.run_id AND
 (v.row_id IN ('legacy-error:'||e.run_id||':'||CAST(e.error_ordinal AS TEXT),'legacy-scheduled:'||e.run_id||':'||CAST(e.error_ordinal AS TEXT))
 OR EXISTS (SELECT 1 FROM mwe_processing_legacy_evidence_state event WHERE event.tenant_id=e.tenant_id AND event.run_id=e.run_id AND event.error_ordinal=e.error_ordinal AND v.row_id='legacy-evidence:'||event.evidence_id))
LEFT JOIN mwe_processing_legacy_evidence_state p ON p.evidence_id=(SELECT receipt.evidence_id FROM mwe_processing_legacy_evidence_state receipt
 WHERE receipt.tenant_id=e.tenant_id AND receipt.run_id=e.run_id AND receipt.error_ordinal=e.error_ordinal AND receipt.error_digest=e.error_digest
 AND (v.row_id NOT LIKE 'legacy-evidence:%' OR v.row_id='legacy-evidence:'||receipt.evidence_id)
 ORDER BY receipt.evidence_at DESC,receipt.evidence_id DESC LIMIT 1);

CREATE VIEW mwe_processing_stage_retry_queue AS
SELECT v.*,CASE WHEN v.kind='legacy' THEN 'legacy_record' ELSE 'verified_v2' END AS evidence_basis,e.error_ordinal AS original_error_ordinal,e.error_digest AS original_error_digest,
 p.linked_job_id,p.action AS legacy_action,p.actor AS legacy_actor,p.evidence_at AS legacy_evidence_at,
 l.dead_letter_id AS legacy_dead_letter_id,l.run_status AS legacy_run_status
FROM (SELECT j.*, s.id AS row_id, s.id AS step_id, s.status, s.stage, s.phase, s.unit_key,
 s.step_attempt, s.dispatch_seq, s.retry_count, s.max_retries, s.next_run_at, s.deadline_at, s.lease_expires_at,
 s.required_for_ready, s.required_for_completion, s.error_class, s.error_code, s.last_error_event_id,
 s.updated_at AS observed_at
FROM mwe_processing_job_state j JOIN processing_steps s ON s.job_id=j.job_id
WHERE s.status IN ('enqueue_pending','queued','running','waiting_external','retry_wait','failed','blocked')
UNION ALL
SELECT '',l.tenant_id,l.knowledge_base_id,l.datasource_id,l.external_id,l.run_id,'','legacy',NULL,'','','',NULL,FALSE,FALSE,NULL,FALSE,'legacy_unverified','unknown','unknown',l.run_status,FALSE,l.title,'',l.source_name,l.kb_name,l.started_at,l.updated_at,NULL,l.finished_at,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'legacy-error:'||l.run_id||':'||CAST(l.error_ordinal AS TEXT),'',l.retry_state,l.stage,'legacy','',
 NULL,NULL,NULL,NULL,NULL,NULL,NULL,FALSE,FALSE,l.error_class,l.error_code,NULL,l.observed_at
FROM mwe_processing_legacy_error_state l WHERE l.retry_state='scheduled' AND NOT EXISTS (SELECT 1 FROM mwe_processing_legacy_evidence_state p WHERE p.tenant_id=l.tenant_id AND p.run_id=l.run_id
 AND p.error_ordinal=l.error_ordinal AND p.error_digest=l.error_digest AND p.action IN ('late_completion','manual_confirmed','recovered','policy_skipped'))) v
LEFT JOIN mwe_processing_legacy_run_state l ON v.kind='legacy' AND l.tenant_id=v.tenant_id AND l.run_id=v.run_id AND l.datasource_id=v.datasource_id
LEFT JOIN mwe_processing_legacy_error_state e ON l.tenant_id=e.tenant_id AND l.run_id=e.run_id AND
 (v.row_id IN ('legacy-error:'||e.run_id||':'||CAST(e.error_ordinal AS TEXT),'legacy-scheduled:'||e.run_id||':'||CAST(e.error_ordinal AS TEXT))
 OR EXISTS (SELECT 1 FROM mwe_processing_legacy_evidence_state event WHERE event.tenant_id=e.tenant_id AND event.run_id=e.run_id AND event.error_ordinal=e.error_ordinal AND v.row_id='legacy-evidence:'||event.evidence_id))
LEFT JOIN mwe_processing_legacy_evidence_state p ON p.evidence_id=(SELECT receipt.evidence_id FROM mwe_processing_legacy_evidence_state receipt
 WHERE receipt.tenant_id=e.tenant_id AND receipt.run_id=e.run_id AND receipt.error_ordinal=e.error_ordinal AND receipt.error_digest=e.error_digest
 AND (v.row_id NOT LIKE 'legacy-evidence:%' OR v.row_id='legacy-evidence:'||receipt.evidence_id)
 ORDER BY receipt.evidence_at DESC,receipt.evidence_id DESC LIMIT 1);

CREATE VIEW mwe_processing_attempt_timeline AS
SELECT v.*,CASE WHEN v.kind='legacy' THEN 'legacy_record' ELSE 'verified_v2' END AS evidence_basis,e.error_ordinal AS original_error_ordinal,e.error_digest AS original_error_digest,
 p.linked_job_id,p.action AS legacy_action,p.actor AS legacy_actor,p.evidence_at AS legacy_evidence_at,
 l.dead_letter_id AS legacy_dead_letter_id,l.run_status AS legacy_run_status
FROM (SELECT j.*, CAST(e.id AS TEXT) AS row_id, e.id AS event_id, e.step_id,
 COALESCE(s.stage,'') AS stage, e.event_type, e.to_state AS status, e.job_revision AS event_revision,
 e.step_attempt, e.dispatch_seq, e.from_state, e.error_class, e.error_code,
 e.actor, e.action, e.operation_request_id, e.queue_task_id, e.trace_id,
 e.resolves_event_id, e.resolution_type, e.created_at AS observed_at
FROM processing_events e JOIN mwe_processing_job_state j ON j.job_id=e.job_id AND j.tenant_id=e.tenant_id
LEFT JOIN processing_steps s ON s.id=e.step_id AND s.job_id=e.job_id
UNION ALL
SELECT '',l.tenant_id,l.knowledge_base_id,l.datasource_id,l.external_id,l.run_id,'','legacy',NULL,'','','',NULL,FALSE,FALSE,NULL,FALSE,'legacy_unverified','unknown','unknown',l.run_status,FALSE,l.title,'',l.source_name,l.kb_name,l.started_at,l.updated_at,NULL,l.finished_at,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'legacy-error:'||l.run_id||':'||CAST(l.error_ordinal AS TEXT),NULL,'',l.stage,'legacy_error','failed',NULL,
 NULL,NULL,'',l.error_class,CASE WHEN l.error_code<>'' THEN l.error_code ELSE 'LEGACY_UNVERIFIED' END,
 '','','','','',NULL,'',l.observed_at FROM mwe_processing_legacy_error_state l
UNION ALL
SELECT '',l.tenant_id,l.knowledge_base_id,l.datasource_id,l.external_id,l.run_id,l.knowledge_id,'legacy',NULL,l.source_revision,'','',NULL,FALSE,FALSE,NULL,FALSE,'legacy_unverified','unknown','unknown',l.run_status,FALSE,l.title,'',l.source_name,l.kb_name,l.started_at,l.updated_at,NULL,l.finished_at,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,
 'legacy-evidence:'||l.evidence_id,NULL,'',l.stage,'legacy_evidence',l.action,NULL,
 l.attempt,NULL,'','','',l.actor,l.action,l.operation_request_id,'','',NULL,l.action,l.evidence_at
FROM mwe_processing_legacy_evidence_state l) v
LEFT JOIN mwe_processing_legacy_run_state l ON v.kind='legacy' AND l.tenant_id=v.tenant_id AND l.run_id=v.run_id AND l.datasource_id=v.datasource_id
LEFT JOIN mwe_processing_legacy_error_state e ON l.tenant_id=e.tenant_id AND l.run_id=e.run_id AND
 (v.row_id IN ('legacy-error:'||e.run_id||':'||CAST(e.error_ordinal AS TEXT),'legacy-scheduled:'||e.run_id||':'||CAST(e.error_ordinal AS TEXT))
 OR EXISTS (SELECT 1 FROM mwe_processing_legacy_evidence_state event WHERE event.tenant_id=e.tenant_id AND event.run_id=e.run_id AND event.error_ordinal=e.error_ordinal AND v.row_id='legacy-evidence:'||event.evidence_id))
LEFT JOIN mwe_processing_legacy_evidence_state p ON p.evidence_id=(SELECT receipt.evidence_id FROM mwe_processing_legacy_evidence_state receipt
 WHERE receipt.tenant_id=e.tenant_id AND receipt.run_id=e.run_id AND receipt.error_ordinal=e.error_ordinal AND receipt.error_digest=e.error_digest
 AND (v.row_id NOT LIKE 'legacy-evidence:%' OR v.row_id='legacy-evidence:'||receipt.evidence_id)
 ORDER BY receipt.evidence_at DESC,receipt.evidence_id DESC LIMIT 1);

CREATE VIEW mwe_processing_unresolved_incidents AS
SELECT v.*,CASE WHEN v.kind='legacy' THEN 'legacy_record' ELSE 'verified_v2' END AS evidence_basis,e.error_ordinal AS original_error_ordinal,e.error_digest AS original_error_digest,
 p.linked_job_id,p.action AS legacy_action,p.actor AS legacy_actor,p.evidence_at AS legacy_evidence_at,
 l.dead_letter_id AS legacy_dead_letter_id,l.run_status AS legacy_run_status
FROM (SELECT e.job_id,e.tenant_id,e.knowledge_base_id,e.datasource_id,e.external_id,e.run_id,e.knowledge_id,e.kind,e.generation,e.source_revision,e.configuration_revision,e.pipeline_fingerprint,e.revision,e.is_current,e.is_published,e.publication_epoch,e.rollback_pin,e.retirement_state,e.readiness,e.completeness,e.job_status,e.plan_sealed,e.title,e.folder_path,e.source_name,e.kb_name,e.created_at,e.updated_at,e.published_at,e.finished_at,e.steps_total,e.steps_succeeded,e.steps_problem,e.cleanup_problem,e.next_retry_at,e.heartbeat_at,e.resources_active,e.charged_bytes,e.estimated_index_bytes,e.doc_type,e.native_raw_bytes,e.native_pages,e.native_units,e.images,e.media_bytes,e.active_stage,e.row_id,e.event_id,e.step_id,e.stage,e.event_type,e.status,e.event_revision,e.step_attempt,e.dispatch_seq,e.from_state,e.error_class,e.error_code,e.actor,e.action,e.operation_request_id,e.queue_task_id,e.trace_id,e.resolves_event_id,e.resolution_type,e.observed_at FROM mwe_processing_attempt_timeline e
WHERE COALESCE(e.error_code,'')<>'' AND NOT EXISTS
 (SELECT 1 FROM processing_events r WHERE r.tenant_id=e.tenant_id AND r.job_id=e.job_id
 AND r.resolves_event_id=e.event_id AND COALESCE(r.resolution_type,'')<>'') AND e.kind<>'legacy'
UNION ALL
SELECT '',l.tenant_id,l.knowledge_base_id,l.datasource_id,l.external_id,l.run_id,'','legacy',NULL,'','','',NULL,FALSE,FALSE,NULL,FALSE,'legacy_unverified','unknown','unknown',l.run_status,FALSE,l.title,'',l.source_name,l.kb_name,l.started_at,l.updated_at,NULL,l.finished_at,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'legacy-error:'||l.run_id||':'||CAST(l.error_ordinal AS TEXT),NULL,'',l.stage,'legacy_error','failed',NULL,
 NULL,NULL,'',l.error_class,CASE WHEN l.error_code<>'' THEN l.error_code ELSE 'LEGACY_UNVERIFIED' END,
 '','','','','',NULL,'',l.observed_at FROM mwe_processing_legacy_error_state l WHERE NOT EXISTS (SELECT 1 FROM mwe_processing_legacy_evidence_state p WHERE p.tenant_id=l.tenant_id AND p.run_id=l.run_id
 AND p.error_ordinal=l.error_ordinal AND p.error_digest=l.error_digest AND p.action IN ('late_completion','manual_confirmed','recovered','policy_skipped'))) v
LEFT JOIN mwe_processing_legacy_run_state l ON v.kind='legacy' AND l.tenant_id=v.tenant_id AND l.run_id=v.run_id AND l.datasource_id=v.datasource_id
LEFT JOIN mwe_processing_legacy_error_state e ON l.tenant_id=e.tenant_id AND l.run_id=e.run_id AND
 (v.row_id IN ('legacy-error:'||e.run_id||':'||CAST(e.error_ordinal AS TEXT),'legacy-scheduled:'||e.run_id||':'||CAST(e.error_ordinal AS TEXT))
 OR EXISTS (SELECT 1 FROM mwe_processing_legacy_evidence_state event WHERE event.tenant_id=e.tenant_id AND event.run_id=e.run_id AND event.error_ordinal=e.error_ordinal AND v.row_id='legacy-evidence:'||event.evidence_id))
LEFT JOIN mwe_processing_legacy_evidence_state p ON p.evidence_id=(SELECT receipt.evidence_id FROM mwe_processing_legacy_evidence_state receipt
 WHERE receipt.tenant_id=e.tenant_id AND receipt.run_id=e.run_id AND receipt.error_ordinal=e.error_ordinal AND receipt.error_digest=e.error_digest
 AND (v.row_id NOT LIKE 'legacy-evidence:%' OR v.row_id='legacy-evidence:'||receipt.evidence_id)
 ORDER BY receipt.evidence_at DESC,receipt.evidence_id DESC LIMIT 1);

CREATE VIEW mwe_processing_lifecycle_inconsistencies AS
SELECT v.*,CASE WHEN v.kind='legacy' THEN 'legacy_record' ELSE 'verified_v2' END AS evidence_basis,e.error_ordinal AS original_error_ordinal,e.error_digest AS original_error_digest,
 p.linked_job_id,p.action AS legacy_action,p.actor AS legacy_actor,p.evidence_at AS legacy_evidence_at,
 l.dead_letter_id AS legacy_dead_letter_id,l.run_status AS legacy_run_status
FROM (SELECT j.*, 'READY_NOT_PUBLISHED:' || j.job_id AS row_id, 'READY_NOT_PUBLISHED' AS status, '' AS stage,
 '' AS step_id, j.updated_at AS observed_at FROM mwe_processing_job_state j  WHERE j.is_current AND NOT j.is_published AND j.readiness='ready' AND (unixepoch('now') - unixepoch(j.updated_at))>300
UNION ALL
SELECT j.*, 'PLAN_UNSEALED:' || j.job_id AS row_id, 'PLAN_UNSEALED' AS status, '' AS stage,
 '' AS step_id, j.updated_at AS observed_at FROM mwe_processing_job_state j  WHERE j.is_current AND NOT j.plan_sealed AND (unixepoch('now') - unixepoch(j.created_at))>300
UNION ALL
SELECT j.*, 'LEASE_EXPIRED:' || s.id AS row_id, 'LEASE_EXPIRED' AS status, s.stage AS stage,
 s.id AS step_id, j.updated_at AS observed_at FROM mwe_processing_job_state j JOIN processing_steps s ON s.job_id=j.job_id WHERE s.status='running' AND (unixepoch('now') - unixepoch(s.lease_expires_at))>0
UNION ALL
SELECT j.*, 'NO_PROGRESS:' || s.id AS row_id, 'NO_PROGRESS' AS status, s.stage AS stage,
 s.id AS step_id, j.updated_at AS observed_at FROM mwe_processing_job_state j JOIN processing_steps s ON s.job_id=j.job_id WHERE s.status='running' AND (unixepoch('now') - unixepoch(s.lease_expires_at))<0 AND (unixepoch('now') - unixepoch(s.progress_at))>300
UNION ALL
SELECT j.*, 'RETRY_OVERDUE:' || s.id AS row_id, 'RETRY_OVERDUE' AS status, s.stage AS stage,
 s.id AS step_id, j.updated_at AS observed_at FROM mwe_processing_job_state j JOIN processing_steps s ON s.job_id=j.job_id WHERE s.status='retry_wait' AND (unixepoch('now') - unixepoch(s.next_run_at))>120
UNION ALL
SELECT j.*, 'PROJECTION_NOT_CONVERGED:' || s.id AS row_id, 'PROJECTION_NOT_CONVERGED' AS status, s.stage AS stage,
 s.id AS step_id, j.updated_at AS observed_at FROM mwe_processing_job_state j JOIN processing_steps s ON s.job_id=j.job_id WHERE j.is_published AND s.phase='projection' AND s.stage<>'retire_previous' AND s.status NOT IN ('succeeded','skipped') AND (unixepoch('now') - unixepoch(j.published_at))>300
UNION ALL
SELECT j.*, 'OUTBOX_OVERDUE:' || s.id AS row_id, 'OUTBOX_OVERDUE' AS status, s.stage AS stage,
 s.id AS step_id, j.updated_at AS observed_at FROM mwe_processing_job_state j JOIN processing_steps s ON s.job_id=j.job_id JOIN task_pending_ops o ON o.tenant_id=j.tenant_id AND o.step_id=s.id AND o.step_attempt=s.step_attempt AND o.dispatch_seq=s.dispatch_seq WHERE s.status IN ('enqueue_pending','queued') AND o.delivered_at IS NULL AND o.op='deliver'
 AND (unixepoch('now') - unixepoch(o.available_at))>120
UNION ALL
SELECT j.*, 'DEAD_LETTER_RUNNING:' || s.id AS row_id, 'DEAD_LETTER_RUNNING' AS status, s.stage AS stage,
 s.id AS step_id, j.updated_at AS observed_at FROM mwe_processing_job_state j JOIN processing_steps s ON s.job_id=j.job_id WHERE s.status='running' AND EXISTS (SELECT 1 FROM task_dead_letters d
 WHERE d.tenant_id=j.tenant_id AND CAST(json_extract(d.payload, '$.job_id') AS TEXT)=j.job_id AND CAST(json_extract(d.payload, '$.step_id') AS TEXT)=s.id
 AND CAST(json_extract(d.payload, '$.generation') AS TEXT)=CAST(j.generation AS TEXT)
 AND CAST(json_extract(d.payload, '$.step_attempt') AS TEXT)=CAST(s.step_attempt AS TEXT) AND CAST(json_extract(d.payload, '$.dispatch_seq') AS TEXT)=CAST(s.dispatch_seq AS TEXT))
UNION ALL
SELECT j.*, 'RESOURCE_MISSING:' || j.job_id AS row_id, 'RESOURCE_MISSING' AS status, '' AS stage,
 '' AS step_id, j.updated_at AS observed_at FROM mwe_processing_job_state j  WHERE j.retirement_state='retained' AND EXISTS (SELECT 1 FROM resource_bindings b
 LEFT JOIN resources r ON r.id=b.resource_id AND r.tenant_id=b.tenant_id
 WHERE b.tenant_id=j.tenant_id AND b.owner_type='processing_job' AND b.owner_id=j.job_id
 AND (r.id IS NULL OR r.state<>'active' OR r.deleted_at IS NOT NULL))
UNION ALL
SELECT j.*, 'COMPATIBILITY_DRIFT:' || j.job_id AS row_id, 'COMPATIBILITY_DRIFT' AS status, '' AS stage,
 '' AS step_id, j.updated_at AS observed_at FROM mwe_processing_job_state j LEFT JOIN knowledges k ON k.id=j.knowledge_id AND k.tenant_id=j.tenant_id WHERE j.is_published AND (k.id IS NULL OR k.deleted_at IS NOT NULL OR k.parse_status NOT IN ('completed','finalizing') OR (j.job_status='succeeded' AND k.parse_status<>'completed') OR k.enable_status<>'enabled')
UNION ALL
SELECT j.*, 'RETIREMENT_BLOCKED:' || s.id AS row_id, 'RETIREMENT_BLOCKED' AS status, s.stage AS stage,
 s.id AS step_id, j.updated_at AS observed_at FROM mwe_processing_job_state j JOIN processing_steps s ON s.job_id=j.job_id WHERE s.phase='retire' AND s.status IN ('failed','blocked')
UNION ALL
SELECT j.*, 'FAQ_GC_STUCK:' || w.id AS row_id, 'FAQ_GC_STUCK' AS status, '' AS stage,
 '' AS step_id, j.updated_at AS observed_at FROM mwe_processing_job_state j JOIN faq_index_writes w ON w.job_id=j.job_id AND w.tenant_id=j.tenant_id WHERE w.state='deleting' AND (unixepoch('now') - unixepoch(w.updated_at))>300
UNION ALL
SELECT j.*, 'RESOURCE_GC_STUCK:' || r.id AS row_id, 'RESOURCE_GC_STUCK' AS status, '' AS stage,
 '' AS step_id, j.updated_at AS observed_at FROM mwe_processing_job_state j JOIN resources r ON r.creation_job_id=j.job_id AND r.tenant_id=j.tenant_id WHERE r.state='deleting' AND (unixepoch('now') - unixepoch(r.updated_at))>300
UNION ALL
SELECT '',l.tenant_id,l.knowledge_base_id,l.datasource_id,'',l.run_id,'','legacy',NULL,'','','',NULL,FALSE,FALSE,NULL,FALSE,'legacy_unverified','unknown','unknown',l.run_status,FALSE,l.source_name||' / '||l.run_id,'',l.source_name,l.kb_name,l.started_at,l.updated_at,NULL,l.finished_at,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'legacy-dead-letter:'||CAST(l.dead_letter_id AS TEXT),'LEGACY_DEAD_LETTER_RUNNING','legacy_scan','',l.updated_at
FROM mwe_processing_legacy_run_state l WHERE l.run_status='running' AND l.dead_letter_id IS NOT NULL
UNION ALL
SELECT '',l.tenant_id,l.knowledge_base_id,l.datasource_id,l.external_id,l.run_id,'','legacy',NULL,'','','',NULL,FALSE,FALSE,NULL,FALSE,'legacy_unverified','unknown','unknown',l.run_status,FALSE,l.title,'',l.source_name,l.kb_name,l.started_at,l.updated_at,NULL,l.finished_at,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'legacy-scheduled:'||l.run_id||':'||CAST(l.error_ordinal AS TEXT),'LEGACY_SCHEDULED_UNVERIFIED',l.stage,'',l.observed_at
FROM mwe_processing_legacy_error_state l WHERE l.retry_state='scheduled' AND NOT EXISTS (SELECT 1 FROM mwe_processing_legacy_evidence_state p WHERE p.tenant_id=l.tenant_id AND p.run_id=l.run_id
 AND p.error_ordinal=l.error_ordinal AND p.error_digest=l.error_digest AND p.action IN ('late_completion','manual_confirmed','recovered','policy_skipped'))
 AND NOT EXISTS (SELECT 1 FROM mwe_processing_legacy_evidence_state p WHERE p.tenant_id=l.tenant_id AND p.run_id=l.run_id AND p.error_ordinal=l.error_ordinal AND p.error_digest=l.error_digest AND p.action='retry_admitted')) v
LEFT JOIN mwe_processing_legacy_run_state l ON v.kind='legacy' AND l.tenant_id=v.tenant_id AND l.run_id=v.run_id AND l.datasource_id=v.datasource_id
LEFT JOIN mwe_processing_legacy_error_state e ON l.tenant_id=e.tenant_id AND l.run_id=e.run_id AND
 (v.row_id IN ('legacy-error:'||e.run_id||':'||CAST(e.error_ordinal AS TEXT),'legacy-scheduled:'||e.run_id||':'||CAST(e.error_ordinal AS TEXT))
 OR EXISTS (SELECT 1 FROM mwe_processing_legacy_evidence_state event WHERE event.tenant_id=e.tenant_id AND event.run_id=e.run_id AND event.error_ordinal=e.error_ordinal AND v.row_id='legacy-evidence:'||event.evidence_id))
LEFT JOIN mwe_processing_legacy_evidence_state p ON p.evidence_id=(SELECT receipt.evidence_id FROM mwe_processing_legacy_evidence_state receipt
 WHERE receipt.tenant_id=e.tenant_id AND receipt.run_id=e.run_id AND receipt.error_ordinal=e.error_ordinal AND receipt.error_digest=e.error_digest
 AND (v.row_id NOT LIKE 'legacy-evidence:%' OR v.row_id='legacy-evidence:'||receipt.evidence_id)
 ORDER BY receipt.evidence_at DESC,receipt.evidence_id DESC LIMIT 1);
